In [1]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [4]:
A*B, np.dot(A,B), np.dot(B,A)

(array([[ 5, 12],
        [21, 32]]),
 array([[19, 22],
        [43, 50]]),
 array([[23, 34],
        [31, 46]]))

In [23]:
A = np.array([[1,2],[3,4],[5,6]])
B1 = np.array([[7],[8]])
B2 = np.array([[[7],[8]]])
B3 = np.array([7,8])
print(f'A : {A.shape}')
print(f'B1 : {B1.shape}')
print(B1)
print(f'B2 : {B2.shape}')
print(B2)
print(f'B3 : {B3.shape}')
print(B3)

A : (3, 2)
B1 : (2, 1)
[[7]
 [8]]
B2 : (1, 2, 1)
[[[7]
  [8]]]
B3 : (2,)
[7 8]


In [24]:
result1 = np.dot(A,B1)
result2 = np.dot(A,B2)
result3 = np.dot(A,B3)

In [25]:
print(f'A*B1 : {result1.shape}')
print(result1)
print(f'A*B2 : {result2.shape}')
print(result2)

print(f'A*B3 : {result3.shape}')
print(result3)


A*B1 : (3, 1)
[[23]
 [53]
 [83]]
A*B2 : (3, 1, 1)
[[[23]]

 [[53]]

 [[83]]]
A*B3 : (3,)
[23 53 83]


In [59]:
A = np.array([[[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]],
              [[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]],
              [[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]],
              [[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]]])
A.shape

(4, 2, 3, 2)

In [67]:
B1 = np.array([[7],[8]])
B2 = np.array([[[7],[8]]])
B3 = np.array([[[[[7],[8]],[[7],[8]],[[7],[8]]]]])

print(f'B1 : {B1.shape}')
print(f'B2 : {B2.shape}')
print(f'B3 : {B3.shape}')


B1 : (2, 1)
B2 : (1, 2, 1)
B3 : (1, 1, 3, 2, 1)


In [68]:
result1 = np.dot(A,B1)
result2 = np.dot(A,B2)
result3 = np.dot(A,B3)
print(f'A*B1 : {result1.shape}')
# print(result1)
print(f'A*B2 : {result2.shape}')
# print(result2)
print(f'A*B3 : {result3.shape}')
# print(result3)


A*B1 : (4, 2, 3, 1)
A*B2 : (4, 2, 3, 1, 1)
A*B3 : (4, 2, 3, 1, 1, 3, 1)
