In [1]:
import pandas as pd
import os

path = r'D:\elice_python\GAS_5\pytest_machine'
os.chdir(path)

In [2]:
import pandas as pd
import os

data = pd.read_csv('income.csv')
print(data.columns.values)
print(data.head(3))
print(data.shape)
print(data.info())

['age' 'workclass' 'education' 'educationNumber' 'maritalStatus'
 'occupation' 'relationship' 'race' 'gender' 'hourPerWeek' 'nativeCountry'
 'income']
   age          workclass   education  educationNumber        maritalStatus  \
0   39          State-gov   Bachelors               13        Never-married   
1   50   Self-emp-not-inc   Bachelors               13   Married-civ-spouse   
2   38            Private     HS-grad                9             Divorced   

           occupation    relationship  race gender  hourPerWeek  \
0        Adm-clerical   Not-in-family     4   Male           40   
1     Exec-managerial         Husband     4   Male           13   
2   Handlers-cleaners   Not-in-family     4   Male           40   

    nativeCountry  income  
0   United-States       0  
1   United-States       0  
2   United-States       0  
(32561, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 12 columns):
 #   Column           Non-Null

In [3]:
data.columns

Index(['age', 'workclass', 'education', 'educationNumber', 'maritalStatus',
       'occupation', 'relationship', 'race', 'gender', 'hourPerWeek',
       'nativeCountry', 'income'],
      dtype='object')

In [4]:
import numpy as np
for col in data.columns:
    print(col, np.unique(data[col]))

age [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40
 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88
 90]
workclass [' ?' ' Federal-gov' ' Local-gov' ' Never-worked' ' Private'
 ' Self-emp-inc' ' Self-emp-not-inc' ' State-gov' ' Without-pay']
education [' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college']
educationNumber [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
maritalStatus [' Divorced' ' Married-AF-spouse' ' Married-civ-spouse'
 ' Married-spouse-absent' ' Never-married' ' Separated' ' Widowed']
occupation [' ?' ' Adm-clerical' ' Armed-Forces' ' Craft-repair' ' Exec-managerial'
 ' Farming-fishing' ' Handlers-cleaners' ' Machine-op-inspct'
 ' Other-service' ' Priv-house-serv' ' Prof-specialty' ' Protective-serv'
 ' Sales' ' Te

worklcass를 비롯 몇몇 컬럼에 ' ?'라는 NA에 해당하는 값이 들어 있으며, 모든 값의 앞에 공백 문자가 들어가 있다. 

### skipinitalspace = True
로 두고 데이터를 불러오면 값의 처음에 있는 공백들을 remove 해준다.

In [5]:
data = pd.read_csv('income.csv', skipinitialspace=True)
print(data.shape)
for col in data.columns:
    print(col, np.unique(data[col]))

(32561, 12)
age [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40
 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88
 90]
workclass ['?' 'Federal-gov' 'Local-gov' 'Never-worked' 'Private' 'Self-emp-inc'
 'Self-emp-not-inc' 'State-gov' 'Without-pay']
education ['10th' '11th' '12th' '1st-4th' '5th-6th' '7th-8th' '9th' 'Assoc-acdm'
 'Assoc-voc' 'Bachelors' 'Doctorate' 'HS-grad' 'Masters' 'Preschool'
 'Prof-school' 'Some-college']
educationNumber [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
maritalStatus ['Divorced' 'Married-AF-spouse' 'Married-civ-spouse'
 'Married-spouse-absent' 'Never-married' 'Separated' 'Widowed']
occupation ['?' 'Adm-clerical' 'Armed-Forces' 'Craft-repair' 'Exec-managerial'
 'Farming-fishing' 'Handlers-cleaners' 'Machine-op-inspct' 'Other-service'
 'Priv-house-serv' 'Prof-specialty' 'Protective-serv' 'Sales'
 'Tech-support' 'Transport-moving']
re

### 특정 문자가  있는 행 삭제

In [6]:
for col in data.columns:
    data = data[data[col] !='?']
    
for col in data.columns:
    print(col, np.unique(data[col]))

age [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40
 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 88 90]
workclass ['Federal-gov' 'Local-gov' 'Private' 'Self-emp-inc' 'Self-emp-not-inc'
 'State-gov' 'Without-pay']
education ['10th' '11th' '12th' '1st-4th' '5th-6th' '7th-8th' '9th' 'Assoc-acdm'
 'Assoc-voc' 'Bachelors' 'Doctorate' 'HS-grad' 'Masters' 'Preschool'
 'Prof-school' 'Some-college']
educationNumber [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
maritalStatus ['Divorced' 'Married-AF-spouse' 'Married-civ-spouse'
 'Married-spouse-absent' 'Never-married' 'Separated' 'Widowed']
occupation ['Adm-clerical' 'Armed-Forces' 'Craft-repair' 'Exec-managerial'
 'Farming-fishing' 'Handlers-cleaners' 'Machine-op-inspct' 'Other-service'
 'Priv-house-serv' 'Prof-specialty' 'Protective-serv' 'Sales'
 'Tech-support' 'Transport-moving']
relationship ['Husband' 'Not-in-family' '

In [7]:
print(data.shape)

(30162, 12)


In [9]:
print(data.columns.values)
data.head(2)

['age' 'workclass' 'education' 'educationNumber' 'maritalStatus'
 'occupation' 'relationship' 'race' 'gender' 'hourPerWeek' 'nativeCountry'
 'income']


age         workclass  education  educationNumber       maritalStatus  \
0   39         State-gov  Bachelors               13       Never-married   
1   50  Self-emp-not-inc  Bachelors               13  Married-civ-spouse   

        occupation   relationship  race gender  hourPerWeek  nativeCountry  \
0     Adm-clerical  Not-in-family     4   Male           40  United-States   
1  Exec-managerial        Husband     4   Male           13  United-States   

   income  
0       0  
1       0

In [27]:
print(data.educationNumber.value_counts())

educationNumber
9     9840
10    6678
13    5044
14    1627
11    1307
7     1048
12    1008
6      820
4      557
15     542
5      455
8      377
16     375
3      288
2      151
1       45
Name: count, dtype: int64


In [ ]:
for col in ['workclass','education','maritalStatus','occupation','relationship','gender' , 'nativeCountry']:
    print(data[col].value_counts(),'\n')

In [20]:
data[data['nativeCountry'] == 'Holand-Netherlands']

age workclass     education  educationNumber  maritalStatus  \
19609   32   Private  Some-college               10  Never-married   

              occupation    relationship  race  gender  hourPerWeek  \
19609  Machine-op-inspct  Other-relative     4  Female           40   

            nativeCountry  income  
19609  Holand-Netherlands       0

In [22]:
X = data.loc[:, 'age':'nativeCountry']
y = data.loc[:,'income']
print(data.shape, X.shape, y.shape)

(30162, 12) (30162, 11) (30162,)


In [23]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 0 to 32560
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              30162 non-null  int64 
 1   workclass        30162 non-null  object
 2   education        30162 non-null  object
 3   educationNumber  30162 non-null  int64 
 4   maritalStatus    30162 non-null  object
 5   occupation       30162 non-null  object
 6   relationship     30162 non-null  object
 7   race             30162 non-null  int64 
 8   gender           30162 non-null  object
 9   hourPerWeek      30162 non-null  int64 
 10  nativeCountry    30162 non-null  object
dtypes: int64(4), object(7)
memory usage: 2.8+ MB


race는 dtype이 int64지만 실제로는 범주형이다.

이를 숫자형 그대로 사용하게 되면 get_dummies() 메서드가 이를 연속형으로 간주하기 때문에, 컬럼의 성격에 맞게 수정해줄 필요가 있다.

- 원-핫 인코딩을 하기 위해 우선 String으로 변환한다.

In [24]:
race_series = X['race'].apply(str)
race_series

0        4
1        4
2        4
3        3
4        3
        ..
32556    4
32557    4
32558    4
32559    4
32560    4
Name: race, Length: 30162, dtype: object

In [25]:
# del X['race']
# X.info()

In [26]:
X['race'] = race_series
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 0 to 32560
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              30162 non-null  int64 
 1   workclass        30162 non-null  object
 2   education        30162 non-null  object
 3   educationNumber  30162 non-null  int64 
 4   maritalStatus    30162 non-null  object
 5   occupation       30162 non-null  object
 6   relationship     30162 non-null  object
 7   race             30162 non-null  object
 8   gender           30162 non-null  object
 9   hourPerWeek      30162 non-null  int64 
 10  nativeCountry    30162 non-null  object
dtypes: int64(3), object(8)
memory usage: 2.8+ MB


수치형과 범주형을 분리한다.

In [29]:
X_num = X[['age','educationNumber', 'hourPerWeek']]
X_cat = X[['workclass', 'education', 'maritalStatus', 'occupation', 
           'relationship', 'race', 'gender', 'nativeCountry']]


종속변수 income은 범주형이지만, 이미 0, 1로 인코딩되어 있으므로 다시 one-hot 인코딩을 해줄 필요가 없다. (다중분류 상황에서는 해주어야 한다.)

수치형 데이터 정규화

In [30]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X_mms = mms.fit_transform(X_num)

In [32]:
print(X_mms)
print(type(X_mms))

[[0.30136986 0.8        0.39795918]
 [0.45205479 0.8        0.12244898]
 [0.28767123 0.53333333 0.39795918]
 ...
 [0.56164384 0.53333333 0.39795918]
 [0.06849315 0.53333333 0.19387755]
 [0.47945205 0.53333333 0.39795918]]
<class 'numpy.ndarray'>


최소를 0, 최대를 1로 하는 MinMax 정규화 (최소최대정규화).
평균을 0, 표준편차를 1로 하는 표준화 정규화(StandardScaler)도 있으나,
일반적으로 MinMax 정규화를 더 많이 사용한다

범주형 데이터 원핫 인코딩

In [35]:
X_hot = pd.get_dummies(X_cat)
print(X_hot.columns.values)
print(type(X_hot))
X_hot.head()

['workclass_Federal-gov' 'workclass_Local-gov' 'workclass_Private'
 'workclass_Self-emp-inc' 'workclass_Self-emp-not-inc'
 'workclass_State-gov' 'workclass_Without-pay' 'education_10th'
 'education_11th' 'education_12th' 'education_1st-4th' 'education_5th-6th'
 'education_7th-8th' 'education_9th' 'education_Assoc-acdm'
 'education_Assoc-voc' 'education_Bachelors' 'education_Doctorate'
 'education_HS-grad' 'education_Masters' 'education_Preschool'
 'education_Prof-school' 'education_Some-college' 'maritalStatus_Divorced'
 'maritalStatus_Married-AF-spouse' 'maritalStatus_Married-civ-spouse'
 'maritalStatus_Married-spouse-absent' 'maritalStatus_Never-married'
 'maritalStatus_Separated' 'maritalStatus_Widowed'
 'occupation_Adm-clerical' 'occupation_Armed-Forces'
 'occupation_Craft-repair' 'occupation_Exec-managerial'
 'occupation_Farming-fishing' 'occupation_Handlers-cleaners'
 'occupation_Machine-op-inspct' 'occupation_Other-service'
 'occupation_Priv-house-serv' 'occupation_Prof-specialt

workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
0                  False                False              False   
1                  False                False              False   
2                  False                False               True   
3                  False                False               True   
4                  False                False               True   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc  workclass_State-gov  \
0                   False                       False                 True   
1                   False                        True                False   
2                   False                       False                False   
3                   False                       False                False   
4                   False                       False                False   

   workclass_Without-pay  education_10th  education_11th  education_12th  ...  \
0                  False           False           False           False  ...   
1                  False           False           False           False  ...   
2                  False           False           False           False  ...   
3                  False           False            True           False  ...   
4                  False           False           False           False  ...   

   nativeCountry_Portugal  nativeCountry_Puerto-Rico  nativeCountry_Scotland  \
0                   False                      False                   False   
1                   False                      False                   False   
2                   False                      False                   False   
3                   False                      False                   False   
4                   False                      False                   False   

   nativeCountry_South  nativeCountry_Taiwan  nativeCountry_Thailand  \
0                False                 False                   False   
1                False                 False                   False   
2                False                 False                   False   
3                False                 False                   False   
4                False                 False                   False   

   nativeCountry_Trinadad&Tobago  nativeCountry_United-States  \
0                          False                         True   
1                          False                         True   
2                          False                         True   
3                          False                         True   
4                          False                        False   

   nativeCountry_Vietnam  nativeCountry_Yugoslavia  
0                  False                     False  
1                  False                     False  
2                  False                     False  
3                  False                     False  
4                  False                     False  

[5 rows x 98 columns]

get_dummies(X_cat, dtype='int') 으로 지정해야 0, 1로 나온다. (기본값 'bool')

수치형과 범주형 재결합

In [36]:
X_mms.shape, X_hot.shape

((30162, 3), (30162, 98))

In [37]:
X_fin = pd.concat([pd.DataFrame(X_mms, columns=['age', 'educationNumber', 'hourPerWeek'])
                   .reset_index(drop=True),
                  X_hot.reset_index(drop=True)], axis=1)

X_fin.head()

age  educationNumber  hourPerWeek  workclass_Federal-gov  \
0  0.301370         0.800000     0.397959                  False   
1  0.452055         0.800000     0.122449                  False   
2  0.287671         0.533333     0.397959                  False   
3  0.493151         0.400000     0.397959                  False   
4  0.150685         0.800000     0.397959                  False   

   workclass_Local-gov  workclass_Private  workclass_Self-emp-inc  \
0                False              False                   False   
1                False              False                   False   
2                False               True                   False   
3                False               True                   False   
4                False               True                   False   

   workclass_Self-emp-not-inc  workclass_State-gov  workclass_Without-pay  \
0                       False                 True                  False   
1                        True                False                  False   
2                       False                False                  False   
3                       False                False                  False   
4                       False                False                  False   

   ...  nativeCountry_Portugal  nativeCountry_Puerto-Rico  \
0  ...                   False                      False   
1  ...                   False                      False   
2  ...                   False                      False   
3  ...                   False                      False   
4  ...                   False                      False   

   nativeCountry_Scotland  nativeCountry_South  nativeCountry_Taiwan  \
0                   False                False                 False   
1                   False                False                 False   
2                   False                False                 False   
3                   False                False                 False   
4                   False                False                 False   

   nativeCountry_Thailand  nativeCountry_Trinadad&Tobago  \
0                   False                          False   
1                   False                          False   
2                   False                          False   
3                   False                          False   
4                   False                          False   

   nativeCountry_United-States  nativeCountry_Vietnam  \
0                         True                  False   
1                         True                  False   
2                         True                  False   
3                         True                  False   
4                        False                  False   

   nativeCountry_Yugoslavia  
0                     False  
1                     False  
2                     False  
3                     False  
4                     False  

[5 rows x 101 columns]

두 DataFrame을 결합할 때 중복된 index가 있는 경우 index 배당이 잘못 되는 경우가 있으므로
기존 index를 버리고 리셋한다

In [38]:
print(X_fin.shape, y.shape)

(30162, 101) (30162,)


In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_fin, y, stratify=y, random_state=0)

In [40]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)

SVC()

In [41]:
print(model.predict(X_test))
print(model.score(X_test, y_test))

[1 0 0 ... 0 0 0]
0.8311894974141361


In [42]:
X_hot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 0 to 32560
Data columns (total 98 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   workclass_Federal-gov                     30162 non-null  bool 
 1   workclass_Local-gov                       30162 non-null  bool 
 2   workclass_Private                         30162 non-null  bool 
 3   workclass_Self-emp-inc                    30162 non-null  bool 
 4   workclass_Self-emp-not-inc                30162 non-null  bool 
 5   workclass_State-gov                       30162 non-null  bool 
 6   workclass_Without-pay                     30162 non-null  bool 
 7   education_10th                            30162 non-null  bool 
 8   education_11th                            30162 non-null  bool 
 9   education_12th                            30162 non-null  bool 
 10  education_1st-4th                         30162 non-null  bool 

In [44]:
import joblib

model_path = 'D:\\elice_python\GAS_5\\pytest_machine\\models\\'
scaler_name = 'dataprocessing_scaler.joblib'
model_name = 'dataprocessing_svm.joblib'

joblib.dump(mms, os.path.join(model_path, scaler_name))
joblib.dump(model, os.path.join(model_path, model_name))

['D:\\elice_python\\GAS_5\\pytest_machine\\models\\dataprocessing_svm.joblib']

In [2]:
import joblib

model_path = 'D:\\elice_python\GAS_5\\pytest_machine\\models\\'
scaler_name = 'dataprocessing_scaler.joblib'
model_name = 'dataprocessing_svm.joblib'

loaded_scaler = joblib.load(model_path+scaler_name)
loaded_model = joblib.load(model_path+model_name)

테스트 데이터 예측 -- 학습 과정과 같은 전처리를 거쳐준다.

In [3]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = pd.read_csv('income.csv', skipinitialspace=True)

for col in data.columns:
    data = data[data[col] != '?']
    
data_X = data.loc[:,'age':'nativeCountry']
print(data_X.shape)

(30162, 11)


In [4]:
newdata = pd.read_csv('income_test.csv', skipinitialspace=True)

for col in newdata.columns:
    newdata = newdata[newdata[col] != '?']
    
newdata_X = newdata.loc[",'age":'nativeCountry']
print(newdata_X.shape)

(9, 11)


- 새로운 데이터에 훈련데이터를 결합
- 새로운 데이터의 범주형에는 훈련데이터에서 사용된 종류가 다 있지 않을 수 있으므로, 반드시 훈련데이터와 결합한 후 원-핫 인코딩을 해야 한다

In [5]:
data_appended = pd.concat([newdata_X.reset_index(drop=True), data_X.reset_index(drop=True)])
print(data_appended.shape)

(30171, 11)


새로운 데이터의 범주형에 훈련데이터에 없던 종류가 있으면..ㅠㅠ 어쩔 수 없다시는 듯.

In [11]:
race_series = data_appended['race'].apply(str)
data_appended['race'] = race_series
data_appended.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30171 entries, 0 to 30161
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              30171 non-null  int64 
 1   workclass        30171 non-null  object
 2   education        30171 non-null  object
 3   educationNumber  30171 non-null  int64 
 4   maritalStatus    30171 non-null  object
 5   occupation       30171 non-null  object
 6   relationship     30171 non-null  object
 7   race             30171 non-null  object
 8   gender           30171 non-null  object
 9   hourPerWeek      30171 non-null  int64 
 10  nativeCountry    30171 non-null  object
dtypes: int64(3), object(8)
memory usage: 2.8+ MB


In [8]:
X_num = data_appended[['age','educationNumber', 'hourPerWeek']]
X_cat = data_appended[['workclass', 'education', 'maritalStatus', 'occupation', 
           'relationship', 'race', 'gender', 'nativeCountry']]

In [9]:
X_scaled = loaded_scaler.transform(X_num)
X_hot = pd.get_dummies(X_cat)

In [12]:
X_fin = pd.concat([pd.DataFrame(X_scaled, columns=['age','educationNumber', 'hourPerWeek']).reset_index(drop=True),
                   X_hot.reset_index(drop=True)], axis=1)

print(X_fin.shape)

(30171, 101)


In [15]:
X_only_new = X_fin.iloc[:9,:]
print(X_only_new.shape)

(9, 101)


In [16]:
predictions = loaded_model.predict(X_only_new)
print(predictions)

[0 0 1 0 0 0 0 0 1]


In [17]:
data.columns

Index(['age', 'workclass', 'education', 'educationNumber', 'maritalStatus',
       'occupation', 'relationship', 'race', 'gender', 'hourPerWeek',
       'nativeCountry', 'income'],
      dtype='object')

In [332]:
sample =  {'age' : 29, 
          'workclass' : 'Private',
          'education' : 'education_Bachelors', 
          'educationNumber':13, 
          'maritalStatus':'Married-civ-spouse',
       'occupation':'Prof-specialty', 
       'relationship':'relationship_Unmarried', 
       'race':'2', 
       'gender':'Male', 
       'hourPerWeek': 40,
       'nativeCountry':'Korea'}

In [333]:
sample_df = pd.DataFrame([sample])

In [334]:
sample_df

age workclass            education  educationNumber       maritalStatus  \
0   29   Private  education_Bachelors               13  Married-civ-spouse   

       occupation            relationship race gender  hourPerWeek  \
0  Prof-specialty  relationship_Unmarried    2   Male           40   

  nativeCountry  
0         Korea

In [335]:
sample_num = sample_df[['age','educationNumber', 'hourPerWeek']]
sample_cat = sample_df[['workclass', 'education', 'maritalStatus', 'occupation', 
           'relationship', 'race', 'gender', 'nativeCountry']]

In [336]:
sample_dummies = pd.get_dummies(sample_cat)
print(sample_dummies)

   workclass_Private  education_education_Bachelors  \
0               True                           True   

   maritalStatus_Married-civ-spouse  occupation_Prof-specialty  \
0                              True                       True   

   relationship_relationship_Unmarried  race_2  gender_Male  \
0                                 True    True         True   

   nativeCountry_Korea  
0                 True  


In [337]:
for col in X_hot.columns:
    if col not in sample_dummies.columns:
        sample_dummies[col] = False
        
print(sample_dummies.shape)

(1, 101)


C:\Users\Caelu\AppData\Local\Temp\ipykernel_13468\2067122965.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  sample_dummies[col] = False


In [338]:
sample_dummies = sample_dummies[X_hot.columns]
print(sample_dummies.shape)

(1, 98)


In [339]:
import joblib

model_path = 'D:\\elice_python\GAS_5\\pytest_machine\\models\\'
scaler_name = 'dataprocessing_scaler.joblib'
model_name = 'dataprocessing_svm.joblib'

loaded_scaler = joblib.load(model_path+scaler_name)
loaded_model = joblib.load(model_path+model_name)

In [340]:
sample_scaled = loaded_scaler.transform(sample_num)
print(sample_scaled)

[[0.16438356 0.8        0.39795918]]


In [341]:
sample_fin = pd.concat([pd.DataFrame(sample_scaled, columns=['age','educationNumber', 'hourPerWeek']).reset_index(drop=True),
                       sample_dummies.reset_index(drop=True)], axis= 1)

In [342]:
sample_fin.shape

(1, 101)

In [343]:
prediction = loaded_model.predict(sample_fin)

if prediction:
    print('above 50K', prediction)
else:
    print('below 50K', prediction)

above 50K [1]
